on: workflow_dispatch

env:
  PLATFORM:
  PREFIX:
  BUILD_WITH_LTO: y

jobs:
  build_static_wine32:
    runs-on: ubuntu-22.04
    name: A job that builds static-wine32
    steps:
      - name: Build
        uses: ./.github/actions/build
        with:
          build-args: |
            PLATFORM="${{env.PLATFORM}}"
            PREFIX="${{env.PREFIX}}"
            BUILD_WITH_LTO="${{env.BUILD_WITH_LTO}}"
            BUILD_JOBS=8

